require(shiny)

shinyUI(pageWithSidebar(
  headerPanel("FIFA 2015 Presidential Election: A different take including FIFA ranking and corruption"),
  sidebarPanel(
    wellPanel(
      checkboxInput("weigh", strong("Weighted?"),FALSE),
      conditionalPanel(condition = "input.weigh",
                       
                       sliderInput("weight","Corruption index (%) in weighted score (vs. Fifa Ranking)",0,100,50))
    ),
    
    ##UEFA
    checkboxInput("uefa", strong("UEFA"),FALSE),
    conditionalPanel(
      condition = "input.uefa",
      checkboxInput("Albania", "Albania",TRUE),
      checkboxInput("Andorra", "Andorra",TRUE),
      checkboxInput("Armenia", "Armenia",TRUE),
      checkboxInput("Austria", "Austria",TRUE),
      checkboxInput("Azerbaijan", "Azerbaijan",TRUE),
      checkboxInput("Belarus", "Belarus",TRUE),
      checkboxInput("Belgium", "Belgium",TRUE),
      checkboxInput("BosniaandHerzegovina", "Bosnia and Herzegovina",TRUE),
      checkboxInput("Bulgaria", "Bulgaria",TRUE),
      checkboxInput("Croatia", "Croatia",TRUE),
      checkboxInput("Cyprus", "Cyprus",TRUE),
      checkboxInput("CzechRepublic", "Czech Republic",TRUE),
      checkboxInput("Denmark", "Denmark",TRUE),
      checkboxInput("England", "England",TRUE),
      checkboxInput("Estonia", "Estonia",TRUE),
      checkboxInput("FaroeIslands", "Faroe Islands",TRUE),
      checkboxInput("Finland", "Finland",TRUE),
      checkboxInput("France", "France",TRUE),
      checkboxInput("FYRMacedonia", "FYR Macedonia",TRUE),
      checkboxInput("Georgia", "Georgia",TRUE),
      checkboxInput("Germany", "Germany",TRUE),
      checkboxInput("Greece", "Greece",TRUE),
      checkboxInput("Hungary", "Hungary",TRUE),
      checkboxInput("Iceland", "Iceland",TRUE),
      checkboxInput("Israel", "Israel",TRUE),
      checkboxInput("Italy", "Italy",TRUE),
      checkboxInput("Kazakhstan", "Kazakhstan",TRUE),
      checkboxInput("Latvia", "Latvia",TRUE),
      checkboxInput("Liechtenstein", "Liechtenstein",TRUE),
      checkboxInput("Lithuania", "Lithuania",TRUE),
      checkboxInput("Luxembourg", "Luxembourg",TRUE),
      checkboxInput("Malta", "Malta",TRUE),
      checkboxInput("Moldova", "Moldova",TRUE),
      checkboxInput("Montenegro", "Montenegro",TRUE),
      checkboxInput("Netherlands", "Netherlands",TRUE),
      checkboxInput("NorthernIreland", "Northern Ireland",TRUE),
      checkboxInput("Norway", "Norway",TRUE),
      checkboxInput("Poland", "Poland",TRUE),
      checkboxInput("Portugal", "Portugal",TRUE),
      checkboxInput("RepublicofIreland", "Republic of Ireland",TRUE),
      checkboxInput("Romania", "Romania",TRUE),
      checkboxInput("Russia", "Russia",TRUE),
      checkboxInput("SanMarino", "San Marino",TRUE),
      checkboxInput("Scotland", "Scotland",TRUE),
      checkboxInput("Serbia", "Serbia",TRUE),
      checkboxInput("Slovakia", "Slovakia",TRUE),
      checkboxInput("Slovenia", "Slovenia",TRUE),
      checkboxInput("Spain", "Spain",TRUE),
      checkboxInput("Sweden", "Sweden",TRUE),
      checkboxInput("Switzerland", "Switzerland",TRUE),
      checkboxInput("Turkey", "Turkey",TRUE),
      checkboxInput("Ukraine", "Ukraine",TRUE),
      checkboxInput("Wales", "Wales",TRUE)),
    
    ##AFC
    checkboxInput("afc", strong("AFC"),FALSE),
    conditionalPanel(
      condition = "input.afc",
      checkboxInput("Afghanistan", "Afghanistan",FALSE),
      checkboxInput("Australia", "Australia",FALSE),
      checkboxInput("Bahrain", "Bahrain",FALSE),
      checkboxInput("Bangladesh", "Bangladesh",FALSE),
      checkboxInput("Bhutan", "Bhutan",FALSE),
      checkboxInput("BruneiDarussalam", "Brunei Darussalam",FALSE),
      checkboxInput("Cambodia", "Cambodia",FALSE),
      checkboxInput("ChinaPR", "China PR",FALSE),
      checkboxInput("ChineseTaipei", "Chinese Taipei",FALSE),
      checkboxInput("Guam", "Guam",FALSE),
      checkboxInput("HongKong", "Hong Kong",FALSE),
      checkboxInput("India", "India",FALSE),
      checkboxInput("Indonesia", "Indonesia",FALSE),
      checkboxInput("Iran", "Iran",FALSE),
      checkboxInput("Iraq", "Iraq",FALSE),
      checkboxInput("Japan", "Japan",FALSE),
      checkboxInput("Jordan", "Jordan",FALSE),
      checkboxInput("KoreaDPR", "Korea DPR",FALSE),
      checkboxInput("KoreaRepublic", "Korea Republic",FALSE),
      checkboxInput("Kuwait", "Kuwait",FALSE),
      checkboxInput("Kyrgyzstan", "Kyrgyzstan",FALSE),
      checkboxInput("Laos", "Laos",FALSE),
      checkboxInput("Lebanon", "Lebanon",FALSE),
      checkboxInput("Macau", "Macau",FALSE),
      checkboxInput("Malaysia", "Malaysia",FALSE),
      checkboxInput("Maldives", "Maldives",FALSE),
      checkboxInput("Mongolia", "Mongolia",FALSE),
      checkboxInput("Myanmar", "Myanmar",FALSE),
      checkboxInput("Nepal", "Nepal",FALSE),
      checkboxInput("Oman", "Oman",FALSE),
      checkboxInput("Pakistan", "Pakistan",FALSE),
      checkboxInput("Palestine", "Palestine",FALSE),
      checkboxInput("Philippines", "Philippines",FALSE),
      checkboxInput("Qatar", "Qatar",FALSE),
      checkboxInput("SaudiArabia", "Saudi Arabia",FALSE),
      checkboxInput("Singapore", "Singapore",FALSE),
      checkboxInput("SriLanka", "Sri Lanka",FALSE),
      checkboxInput("Syria", "Syria",FALSE),
      checkboxInput("Tajikistan", "Tajikistan",FALSE),
      checkboxInput("Thailand", "Thailand",FALSE),
      checkboxInput("TimorLeste", "Timor-Leste",FALSE),
      checkboxInput("Turkmenistan", "Turkmenistan",FALSE),
      checkboxInput("UnitedArabEmirates", "United Arab Emirates",FALSE),
      checkboxInput("Uzbekistan", "Uzbekistan",FALSE),
      checkboxInput("Vietnam", "Vietnam",FALSE),
      checkboxInput("Yemen", "Yemen",FALSE)),
    
    ##CAF
    checkboxInput("caf", strong("CAF"),FALSE),
    conditionalPanel(
      condition = "input.caf",
      checkboxInput("Algeria", "Algeria",FALSE),
      checkboxInput("Angola", "Angola",FALSE),
      checkboxInput("Benin", "Benin",FALSE),
      checkboxInput("Botswana", "Botswana",FALSE),
      checkboxInput("BurkinaFaso", "Burkina Faso",FALSE),
      checkboxInput("Burundi", "Burundi",FALSE),
      checkboxInput("Cameroon", "Cameroon",FALSE),
      checkboxInput("CapeVerdeIslands", "Cape Verde Islands",FALSE),
      checkboxInput("CentralAfricanRepublic", "Central African Republic",FALSE),
      checkboxInput("Chad", "Chad",FALSE),
      checkboxInput("Comoros", "Comoros",FALSE),
      checkboxInput("Congo", "Congo",FALSE),
      checkboxInput("CongoDR", "Congo DR",FALSE),
      checkboxInput("CotedIvoire", "Côte d'Ivoire",FALSE),
      checkboxInput("Djibouti", "Djibouti",FALSE),
      checkboxInput("Egypt", "Egypt",FALSE),
      checkboxInput("EquatorialGuinea", "Equatorial Guinea",FALSE),
      checkboxInput("Eritrea", "Eritrea",FALSE),
      checkboxInput("Ethiopia", "Ethiopia",FALSE),
      checkboxInput("Gabon", "Gabon",FALSE),
      checkboxInput("Gambia", "Gambia",FALSE),
      checkboxInput("Ghana", "Ghana",FALSE),
      checkboxInput("Guinea", "Guinea",FALSE),
      checkboxInput("GuineaBissau", "Guinea-Bissau",FALSE),
      checkboxInput("Kenya", "Kenya",FALSE),
      checkboxInput("Lesotho", "Lesotho",FALSE),
      checkboxInput("Liberia", "Liberia",FALSE),
      checkboxInput("Libya", "Libya",FALSE),
      checkboxInput("Madagascar", "Madagascar",FALSE),
      checkboxInput("Malawi", "Malawi",FALSE),
      checkboxInput("Mali", "Mali",FALSE),
      checkboxInput("Mauritania", "Mauritania",FALSE),
      checkboxInput("Mauritius", "Mauritius",FALSE),
      checkboxInput("Morocco", "Morocco",FALSE),
      checkboxInput("Mozambique", "Mozambique",FALSE),
      checkboxInput("Namibia", "Namibia",FALSE),
      checkboxInput("Niger", "Niger",FALSE),
      checkboxInput("Nigeria", "Nigeria",FALSE),
      checkboxInput("Rwanda", "Rwanda",FALSE),
      checkboxInput("SaoTomeePrincipe", "São Tomé e Príncipe",FALSE),
      checkboxInput("Senegal", "Senegal",FALSE),
      checkboxInput("Seychelles", "Seychelles",FALSE),
      checkboxInput("SierraLeone", "Sierra Leone",FALSE),
      checkboxInput("Somalia", "Somalia",FALSE),
      checkboxInput("SouthAfrica", "South Africa",FALSE),
      checkboxInput("SouthSudan", "South Sudan",FALSE),
      checkboxInput("Sudan", "Sudan",FALSE),
      checkboxInput("Swaziland", "Swaziland",FALSE),
      checkboxInput("Tanzania", "Tanzania",FALSE),
      checkboxInput("Togo", "Togo",FALSE),
      checkboxInput("Tunisia", "Tunisia",FALSE),
      checkboxInput("Uganda", "Uganda",FALSE),
      checkboxInput("Zambia", "Zambia",FALSE),
      checkboxInput("Zimbabwe", "Zimbabwe",FALSE)),
    
    ##CONCACAF
    checkboxInput("concacaf", strong("CONCACAF"),FALSE),
    conditionalPanel(
      condition = "input.concacaf",
      checkboxInput("Anguilla", "Anguilla",FALSE),
      checkboxInput("AntiguaandBarbuda", "Antigua and Barbuda",FALSE),
      checkboxInput("Aruba", "Aruba",FALSE),
      checkboxInput("Bahamas", "Bahamas",FALSE),
      checkboxInput("Barbados", "Barbados",FALSE),
      checkboxInput("Belize", "Belize",FALSE),
      checkboxInput("Bermuda", "Bermuda",FALSE),
      checkboxInput("BritishVirginIslands", "British Virgin Islands",FALSE),
      checkboxInput("Canada", "Canada",TRUE),
      checkboxInput("CaymanIslands", "Cayman Islands",FALSE),
      checkboxInput("CostaRica", "Costa Rica",FALSE),
      checkboxInput("Cuba", "Cuba",FALSE),
      checkboxInput("Curacao", "Curaçao",FALSE),
      checkboxInput("Dominica", "Dominica",FALSE),
      checkboxInput("DominicanRepublic", "Dominican Republic",FALSE),
      checkboxInput("ElSalvador", "El Salvador",FALSE),
      checkboxInput("Grenada", "Grenada",FALSE),
      checkboxInput("Guatemala", "Guatemala",FALSE),
      checkboxInput("Guyana", "Guyana",FALSE),
      checkboxInput("Haiti", "Haiti",FALSE),
      checkboxInput("Honduras", "Honduras",FALSE),
      checkboxInput("Jamaica", "Jamaica",FALSE),
      checkboxInput("Mexico", "Mexico",FALSE),
      checkboxInput("Montserrat", "Montserrat",FALSE),
      checkboxInput("Nicaragua", "Nicaragua",FALSE),
      checkboxInput("Panama", "Panama",FALSE),
      checkboxInput("PuertoRico", "Puerto Rico",FALSE),
      checkboxInput("StKittsandNevis", "St. Kitts and Nevis",FALSE),
      checkboxInput("StLucia", "St. Lucia",FALSE),
      checkboxInput("StVincentandtheGrenadines", "St. Vincent and the Grenadines",FALSE),
      checkboxInput("Suriname", "Suriname",FALSE),
      checkboxInput("TrinidadandTobago", "Trinidad and Tobago",FALSE),
      checkboxInput("TurksandCaicosIslands", "Turks and Caicos Islands",FALSE),
      checkboxInput("USVirginIslands", "US Virgin Islands",FALSE),
      checkboxInput("USA", "USA",TRUE)),
    
    ##CONMBEOL
    checkboxInput("conmebol", strong("CONMEBOL"),FALSE),
    conditionalPanel(
      condition = "input.conmebol",
      checkboxInput("Argentina", "Argentina",FALSE),
      checkboxInput("Bolivia", "Bolivia",FALSE),
      checkboxInput("Brazil", "Brazil",FALSE),
      checkboxInput("Chile", "Chile",FALSE),
      checkboxInput("Colombia", "Colombia",FALSE),
      checkboxInput("Ecuador", "Ecuador",FALSE),
      checkboxInput("Paraguay", "Paraguay",FALSE),
      checkboxInput("Peru", "Peru",FALSE),
      checkboxInput("Uruguay", "Uruguay",FALSE),
      checkboxInput("Venezuela", "Venezuela",FALSE)),
    
    ##OFC
    checkboxInput("ofc", strong("OFC"),FALSE),
    conditionalPanel(
      condition = "input.ofc",
      checkboxInput("AmericanSamoa", "American Samoa",FALSE),
      checkboxInput("CookIslands", "Cook Islands",FALSE),
      checkboxInput("Fiji", "Fiji",FALSE),
      checkboxInput("NewCaledonia", "New Caledonia",FALSE),
      checkboxInput("NewZealand", "New Zealand",TRUE),
      checkboxInput("PapuaNewGuinea", "Papua New Guinea",FALSE),
      checkboxInput("Samoa", "Samoa",FALSE),
      checkboxInput("SolomonIslands", "Solomon Islands",FALSE),
      checkboxInput("Tahiti", "Tahiti",FALSE),
      checkboxInput("Tonga", "Tonga",FALSE),
      checkboxInput("Vanuatu", "Vanuatu",FALSE)),
    
    
    wellPanel(
      checkboxInput("info", strong("Info"),TRUE),
      conditionalPanel(condition = "input.info",
                      tags$div(
                         HTML("With this application you can select each country that (should have/thought to have) voted for <a href='http://en.wikipedia.org/wiki/Prince_Ali_bin_Hussein' target='_blank'>Prince Ali bin Hussein of Jordan</a>
              in the <a href='http://en.wikipedia.org/wiki/65th_FIFA_Congress' target='_blank'>2015 FIFA Presidency election</a> in which it was the challenger 
              of <a href='http://en.wikipedia.org/wiki/Sepp_Blatter' target='_blank'>Sepp Blatter</a>. 
<br> <br> This application also gives a twist in the way the votes are counted. If you select [Weighted] each vote is corrected for the 
              <a href='http://www.fifa.com/fifa-world-ranking/ranking-table/men/' target='_blank'>FIFA ranking</a> of each country and for
              the <a href='http://www.transparency.org/research/cpi/overview' target='_blank'>CPI corruption index</a> of each country. The weight you give to each of these two aspects can be regulated with the slider. A higher percentage means that the corruption index receives
              more weight, while a percentage of 0% results in the sole inclusion of the FIFA ranking. As such it is visualized what happens if we take the football legacy and corruption of countries
              into account if they vote for the president of FIFA. The main principle should be obvious, it seems strange that 'corrupt' countries who have almost nothing to do with football, have the
              same input as the core nations of football. 
         <br> <br>
         <ul><li>The pie diagram shows the percentage of (weighted) votes that each of the two candidates received.</li>
         <li>You can select the countries, that voted for Ali, per Confederation.</li>
         <li>In the table the information for each association is given regarding the: Confederation, Vote (-1 = Blatter; 1 = Ali), FIFA Ranking, CPI Score, relative FIFA Ranking, relative CPI Score, vote weight, weighted vote (a large negative weighted vote favours Blatter while a large positve vote favours Ali)
</ul>
                             
                              <br> Note. Although the United Kingdom is shown as one the votes are counted and weighted separately for each separate association. For countries that have no CPI ranking the mean of their confederation is used")

                       )
                       
      ))),
      
      mainPanel(
        htmlOutput("gvis"),
        htmlOutput("bar"),
        dataTableOutput("dataout")
      )
    ))
  